name: Release

on:
  release:
    types: [ created ]

permissions:
  contents: write

jobs:
  release-binaries:
    name: Build release binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - uses: icewind1991/attic-action@v1
        with:
          name: ci
          instance: https://cache.icewind.me
          authToken: '${{ secrets.ATTIC_TOKEN }}'
      - run: nix build .#x86_64-unknown-linux-musl
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: result/bin/evtype
          asset_name: evtype
          tag: ${{ github.ref }}
      - name: Upload Daemon binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: result/bin/evtype_daemon
          asset_name: evtype_daemon
          tag: ${{ github.ref }}